### ISSUE TITLE
Arquivo Excel em Test01.R

### ISSUE THREAD

**Issue by brdsio** [claudiolucinda/DieselCost#1]
Oi professor, tudo bem?
O arquivo Teste01.R faz a leitura de um arquivo Excel chamado `USGulf.xlsx` que não está no repositório.
Como faço para conseguir ele?
Obrigado

**Comment by claudiolucinda** [comment]
Tinha dado o commit mas não o push. Agora os dois `xlsx` tão lá. Valeu!
